version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "App1"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        DesiredCount: 1
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-c271fcb9", "subnet-7a041112", "subnet-09d7ac45"]
            SecurityGroups: ["sg-002ac6db3d101f6c3"]
            AssignPublicIp: "ENABLED"
