version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:078861816452:task-definition/taskapp1:7"
        LoadBalancerInfo:
          ContainerName: "App1"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-c271fcb9", "subnet-7a041112", "subnet-09d7ac45"]
            SecurityGroups: ["sg-002ac6db3d101f6c3"]
            AssignPublicIp: "ENABLED"
